CREATE TABLE [dbo].[BucketType] (
 [Id] INT IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_BucketType] PRIMARY KEY CLUSTERED ([Id] ASC)
);

