CREATE TABLE [dbo].[Currency] (
 [Id] INT IDENTITY (1, 1) NOT NULL,
    [Code] NVARCHAR(10) NOT NULL,
    [ExchangeRateToUSD] DECIMAL(18,6) NOT NULL,
    [UpdateDT] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [PK_Currency] PRIMARY KEY CLUSTERED ([Id] ASC)
);

