CREATE TABLE [dbo].[SpendRequest] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [ReferenceNumber]    NVARCHAR (50)   NOT NULL,
    [DepartmentId]       INT             NOT NULL,
    [CategoryId]         INT             NOT NULL,
    [EncoderId]          INT             NOT NULL,
    [AssignedToUserId]   INT             NULL,
    [Amount]             DECIMAL (18, 2) NOT NULL,
    [CurrencyId]         INT             NOT NULL,
    [LockedExchangeRate] DECIMAL (18, 6) NOT NULL,
    [VendorId]           INT             NULL,
    [Description]        NVARCHAR (MAX)  NOT NULL,
    [Status]             NVARCHAR (50)   NOT NULL,
    [CreateDT]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [UpdateDT]           DATETIME        DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SpendRequest_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Category] ([Id]),
    CONSTRAINT [FK_SpendRequest_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([Id]),
    CONSTRAINT [FK_SpendRequest_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_SpendRequest_Encoder] FOREIGN KEY ([EncoderId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_SpendRequest_AssignedToUser] FOREIGN KEY ([AssignedToUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_SpendRequest_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id]),
    UNIQUE NONCLUSTERED ([ReferenceNumber] ASC)
);

